import type { Metadata } from "next";
import { DM_Sans, Bebas_Neue } from "next/font/google"; // Modified import
import "./globals.css";
import { WhitelabelProvider } from "./context/WhitelabelContext";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
              </head>
      <body
        className={`${dmSans.variable} ${bebasNeue.variable} antialiased`}
      >
        <WhitelabelProvider>
          {children}
        </WhitelabelProvider>
      </body>
    </html>
  );
}
